version: '3.8'

services:
  api:
    image: temp_proj_new_image
    ports:
      - "80:80"
    environment:
      PROJTEMPPOSTGRES: ${PROJTEMPPOSTGRES}
      MqttSettings__Username: ${MQTT_USERNAME}
      MqttSettings__Password: ${MQTT_PASSWORD}
      MqttSettings__BrokerUrl: ${MQTT_BROKER_URL}
      MqttSettings__ClientId: ${MQTT_CLIENT_ID}
      MqttSettings__Topic: ${MQTT_TOPIC}
