version: "3.3"

services:
  app-database:
    image: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 63307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://app-database:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true -user=root -password=${MYSQL_ROOT_PASSWORD} migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      app-database:
        condition: service_healthy
