name: .NET CI/CD with SonarQube and E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Restore dependencies
        run: dotnet restore api/tempProjNew.sln

      - name: Build solution
        run: dotnet build api/tempProjNew.sln --configuration Release --no-restore

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:~/.dotnet/tools"

      - name: Run SonarQube analysis
        run: dotnet sonarscanner begin /k:"tempProjNew" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.cs.opencover.reportsPaths="api/TestResults/coverage.opencover.xml" /v:"1.0"

      - name: Build for SonarQube
        run: dotnet build api/tempProjNew.sln

      - name: Run tests with coverage
        run: |
          mkdir -p api/TestResults
          dotnet test api/tempProjNew.sln --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=api/TestResults/coverage.opencover.xml /p:CoverletOutputFormat=opencover

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: api/TestResults/coverage.opencover.xml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend/temperature-frontend

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: frontend/temperature-frontend

      - name: Start backend server
        run: dotnet run --project api/ --urls http://localhost:5296 &
        shell: bash

      - name: Start frontend server
        run: npm start &
        working-directory: frontend/temperature-frontend
        shell: bash

      - name: Wait for services to start
        run: sleep 30

      - name: Run frontend tests
        run: npm run playwright:test
        working-directory: frontend/temperature-frontend
