name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Build Docker image
        run: docker build -t temp_proj_new_image .

      - name: Run Docker Compose
        run: |
          echo "PROJ_TEMP_POSTGRES=${{ secrets.PROJTEMPPOSTGRES }}" >> .env
          echo "MQTT_BROKER_ADDRESS=${{ secrets.MQTT_USERNAME }}" >> .env
          docker-compose up -d
